name: check-enviroment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "hello"
          go version
          docker version
          helm version
          kustomize version
          kubectl version
          

